services:
  - type: web
    name: api-nodejs
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        fromDatabase:
          name: api_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: api_db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: api_db
          property: database
      - key: DB_USER
        fromDatabase:
          name: api_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: api_db
          property: password
      - key: JWT_SECRET
        value: tu_jwt_secret_aqui
databases:
  - name: api_db
    databaseName: api_db
    user: api_user